POSTTEST 7

import library

In [4]:
import tensorflow as tf

Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [5]:
random_tensor = tf.random.normal([5,5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.09706679, -0.4379941 ,  0.70537066,  2.0242422 ,  0.6242356 ],
       [ 1.3449932 ,  0.29115355,  1.2268361 ,  0.11070856,  2.6446483 ],
       [ 0.34495565, -0.49888837,  0.20307769,  0.28856617,  1.2878911 ],
       [-0.52085894,  0.7361505 ,  1.0627344 , -2.5137057 , -1.0715206 ],
       [ 0.66625714,  0.50972325, -1.6279899 , -0.7276927 , -2.4246235 ]],
      dtype=float32)>

Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor dan tampilkan isinya

In [6]:
bilanganPrima = [[2, 3, 5, 7, 11],
              [13, 17, 19, 23, 29],
              [31, 37, 41, 43, 47],
              [53, 59, 61, 67, 71],
              [73, 79, 83, 89, 97]]
prime_tensor = tf.convert_to_tensor(bilanganPrima, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

Tampilkan dimensi dari kedua variable tersebut

In [10]:
print(f'Dimensi variabel random_tensor: {random_tensor.shape}',
     f'Dimensi variabel prime_tensor: {prime_tensor.get_shape()}',
     sep='\n')

Dimensi variabel random_tensor: (5, 5)
Dimensi variabel prime_tensor: (5, 5)


Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [12]:
# Perkalian
tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.9413358e-01, -1.3139822e+00,  3.5268533e+00,  1.4169695e+01,
         6.8665915e+00],
       [ 1.7484913e+01,  4.9496102e+00,  2.3309885e+01,  2.5462971e+00,
         7.6694801e+01],
       [ 1.0693625e+01, -1.8458870e+01,  8.3261852e+00,  1.2408345e+01,
         6.0530884e+01],
       [-2.7605524e+01,  4.3432880e+01,  6.4826797e+01, -1.6841829e+02,
        -7.6077957e+01],
       [ 4.8636772e+01,  4.0268135e+01, -1.3512315e+02, -6.4764656e+01,
        -2.3518848e+02]], dtype=float32)>

In [13]:
# Pembagian
tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.04853339, -0.14599803,  0.14107414,  0.28917745,  0.05674869],
       [ 0.10346102,  0.01712668,  0.06457032,  0.00481342,  0.09119477],
       [ 0.0111276 , -0.01348347,  0.00495311,  0.00671084,  0.02740194],
       [-0.00982753,  0.01247713,  0.01742188, -0.03751799, -0.01509184],
       [ 0.00912681,  0.00645219, -0.01961434, -0.00817632, -0.02499612]],
      dtype=float32)>

In [14]:
# Pertambahan
tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.9029332,  2.562006 ,  5.705371 ,  9.024242 , 11.624235 ],
       [14.344994 , 17.291153 , 20.226835 , 23.110708 , 31.644648 ],
       [31.344955 , 36.50111  , 41.20308  , 43.288567 , 48.28789  ],
       [52.47914  , 59.73615  , 62.062733 , 64.4863   , 69.92848  ],
       [73.66626  , 79.50972  , 81.37201  , 88.27231  , 94.57538  ]],
      dtype=float32)>

In [15]:
# Pengurangan
tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -2.0970669,  -3.437994 ,  -4.294629 ,  -4.9757576, -10.375765 ],
       [-11.655006 , -16.708847 , -17.773165 , -22.889292 , -26.355352 ],
       [-30.655045 , -37.49889  , -40.79692  , -42.711433 , -45.71211  ],
       [-53.52086  , -58.26385  , -59.937267 , -69.5137   , -72.07152  ],
       [-72.33374  , -78.49028  , -84.62799  , -89.72769  , -99.42462  ]],
      dtype=float32)>

In [17]:
# Perpangkatan
tf.square(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.00942196, 0.19183883, 0.49754778, 4.097556  , 0.38967004],
       [1.8090068 , 0.08477039, 1.5051268 , 0.01225639, 6.9941645 ],
       [0.1189944 , 0.24888961, 0.04124055, 0.08327044, 1.6586636 ],
       [0.27129403, 0.54191756, 1.1294043 , 6.3187165 , 1.1481563 ],
       [0.4438986 , 0.25981778, 2.650351  , 0.5295367 , 5.878799  ]],
      dtype=float32)>

Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [18]:
print('Nilai maksimum dari Tensor random_tensor berdasarkan kolom:')
for x, y in enumerate(tf.argmax(random_tensor, axis=0)):
    print('Nilai Kolom-%d Baris-%d: %f' % (x + 1, y, random_tensor[x, y].numpy()))

print('\nNilai maksimum dari Tensor random_tensor berdasarkan baris:')
for x, y in enumerate(tf.argmax(random_tensor, axis=1)):
    print('Nilai Baris-%d Kolom-%d: %f' % (x + 1, y, random_tensor[x, y].numpy()))
    
print('\nNilai minimum dari Tensor random_tensor berdasarkan kolom:')
for x, y in enumerate(tf.argmin(random_tensor, axis=0)):
    print('Nilai Kolom-%d Baris-%d: %f' % (x + 1, y, random_tensor[x, y].numpy()))
    
print('\nNilai minimum dari Tensor random_tensor berdasarkan baris:')
for x, y in enumerate(tf.argmin(random_tensor, axis=1)):
    print('Nilai Baris-%d Kolom-%d: %f' % (x + 1, y, random_tensor[x, y].numpy()))

Nilai maksimum dari Tensor random_tensor berdasarkan kolom:
Nilai Kolom-1 Baris-1: -0.437994
Nilai Kolom-2 Baris-3: 0.110709
Nilai Kolom-3 Baris-1: -0.498888
Nilai Kolom-4 Baris-0: -0.520859
Nilai Kolom-5 Baris-1: 0.509723

Nilai maksimum dari Tensor random_tensor berdasarkan baris:
Nilai Baris-1 Kolom-3: 2.024242
Nilai Baris-2 Kolom-4: 2.644648
Nilai Baris-3 Kolom-4: 1.287891
Nilai Baris-4 Kolom-2: 1.062734
Nilai Baris-5 Kolom-0: 0.666257

Nilai minimum dari Tensor random_tensor berdasarkan kolom:
Nilai Kolom-1 Baris-3: 2.024242
Nilai Kolom-2 Baris-2: 1.226836
Nilai Kolom-3 Baris-4: 1.287891
Nilai Kolom-4 Baris-3: -2.513706
Nilai Kolom-5 Baris-4: -2.424623

Nilai minimum dari Tensor random_tensor berdasarkan baris:
Nilai Baris-1 Kolom-1: -0.437994
Nilai Baris-2 Kolom-3: 0.110709
Nilai Baris-3 Kolom-1: -0.498888
Nilai Baris-4 Kolom-3: -2.513706
Nilai Baris-5 Kolom-4: -2.424623


Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [19]:
tf.concat([random_tensor, prime_tensor], axis=0)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-0.09706679, -0.4379941 ,  0.70537066,  2.0242422 ,  0.6242356 ],
       [ 1.3449932 ,  0.29115355,  1.2268361 ,  0.11070856,  2.6446483 ],
       [ 0.34495565, -0.49888837,  0.20307769,  0.28856617,  1.2878911 ],
       [-0.52085894,  0.7361505 ,  1.0627344 , -2.5137057 , -1.0715206 ],
       [ 0.66625714,  0.50972325, -1.6279899 , -0.7276927 , -2.4246235 ],
       [ 2.        ,  3.        ,  5.        ,  7.        , 11.        ],
       [13.        , 17.        , 19.        , 23.        , 29.        ],
       [31.        , 37.        , 41.        , 43.        , 47.        ],
       [53.        , 59.        , 61.        , 67.        , 71.        ],
       [73.        , 79.        , 83.        , 89.        , 97.        ]],
      dtype=float32)>

Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [20]:
# random_tensor
tf.sort(random_tensor.numpy(), direction='DESCENDING')

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.0242422 ,  0.70537066,  0.6242356 , -0.09706679, -0.4379941 ],
       [ 2.6446483 ,  1.3449932 ,  1.2268361 ,  0.29115355,  0.11070856],
       [ 1.2878911 ,  0.34495565,  0.28856617,  0.20307769, -0.49888837],
       [ 1.0627344 ,  0.7361505 , -0.52085894, -1.0715206 , -2.5137057 ],
       [ 0.66625714,  0.50972325, -0.7276927 , -1.6279899 , -2.4246235 ]],
      dtype=float32)>

In [21]:
# prime_tensor
tf.sort(prime_tensor.numpy(), direction='DESCENDING')

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)>